### ISSUE TITLE
Porting an older OpenGL library to modern OpenGL

### ISSUE THREAD

**Issue by jonaslindemann** [ColleagueRiley/RGL#5]
I have an older OpenGL c++ library that I would like to port to modern OpenGL. I was really happy to find RGL.h, which seem to enable this process. Today I used glad to include OpenGL headers. I am having trouble adding RGL.h to the includes without a lot of warnings of redefinitions and missing types. Currently I use the following include in my top-level includes:

```
#pragma once

#include <glad/glad.h>
#include <GL/glu.h>
```

Can RGL.h be used together with glad or do I have to rely completely on RGL.h?

Jonas

**Comment by ColleagueRiley** [comment]
RGL has it's own way of loading opengl functions and it only loads the functions it needs. This makes it so RGL is using less resources than GLAD. RGL currently has no way of changing this as a user. However, it would be very easy for me to make it so you can use GLAD with RGL if that's something you want.

**Comment by ColleagueRiley** [comment]
My mistake, I didn't mean to close the issue.

**Comment by ColleagueRiley** [comment]
Okay, now you should be able to use GLAD instead of RGL's opengl loader by adding `#define RGL_NO_GL_LOADER`

```c
#define RGL_IMPLEMENTATION
#define RGL_NO_GL_LOADER

#include "RGL.h"

#include <glad/glad.h>
#include <GL/glu.h>
```
